### PR TITLE
Origin/quiz page

### PR DESCRIPTION
**Pull request by ellrub**
start of quiz page. nothing finished

### CODE REVIEW

**Comment by DanielaKuester** [comment]
I like the structure of your files and folders. It's easy to find things and I'm looking forward to using the same structure.

The page layout is great for mobile. It's a good start!

**Review by DanielaKuester — APPROVED** [review]
I like the structure of your files and folders. It's easy to find things and I'm looking forward to using the same structure.

The page layout is great for mobile. It's a good start!

**Comment by jeeannyy** [comment]
Nice work!!

**Review by jeeannyy — APPROVED** [review]
Nice work!!

**Review by dela-ger — COMMENTED** [review]
Good job

**Pull request merged**
